# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoaDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveCocoaDemo
 pod 'ReactiveCocoa', '~> 7.0'
 pod 'SnapKit', '~> 4.0.0'
 pod 'SSKitSwift', :git => 'https://github.com/jiazifa/SSKitSwift'
end
